repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
    -   id: isort

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8

-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
        language_version: python3.8
        args: [--line-length=79]

-   repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        entry: ./mypy.sh
