"""Added phone_number colume into the user table.

Revision ID: 4d5fd29c2367
Revises: d562bfa56c73
Create Date: 2021-10-10 04:52:42.843508

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4d5fd29c2367"
down_revision = "d562bfa56c73"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("phone_number", sa.String(length=20), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "phone_number")
    # ### end Alembic commands ###
